name: Docker_Image_Build
on:
  push:
    branches: [ "main" ]
    
jobs:
  Docker_Image_Build-Push:
    runs-on: ubuntu-latest
    
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
       
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: taeheilee/myrepo
          username: taeheilee
          password: dckr_pat_358b_qD9QIeVEDuTdFuJ8Su5bGE
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: chlzzz/myrepo:latest
